package com.integrityengine.ai;

import com.integrityengine.domain.CodeSubmission;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * {@link LlmJudge} backed by the Anthropic Messages API over plain HTTP.
 *
 * <p>Uses the JDK's own {@code java.net.http} client so the project keeps its original
 * dependency set. That choice has a consequence worth stating: there is no JSON library
 * here, so the response is read by targeted extraction rather than a real parser. The
 * request therefore asks the model for a deliberately trivial line-oriented reply
 * instead of JSON — parsing JSON-inside-JSON by hand is where this kind of code breaks.
 *
 * <p>Every failure path returns {@link Optional#empty()}. Nothing here throws, and the
 * API key is never stored in a field, written to a log, or placed in a result.
 */
final class AnthropicLlmJudge implements LlmJudge {

    private static final URI ENDPOINT = URI.create("https://api.anthropic.com/v1/messages");
    private static final String ANTHROPIC_VERSION = "2023-06-01";
    private static final String MODEL = "claude-opus-5";

    private static final Duration CONNECT_TIMEOUT = Duration.ofSeconds(10);
    private static final Duration REQUEST_TIMEOUT = Duration.ofSeconds(30);

    /** Submissions are truncated before being sent; a huge file is not worth the tokens. */
    static final int MAX_SOURCE_CHARS = 20_000;

    private static final Pattern LIKELIHOOD =
            Pattern.compile("(?im)^\\s*LIKELIHOOD\\s*:\\s*([0-9]*\\.?[0-9]+)\\s*$");
    private static final Pattern RATIONALE =
            Pattern.compile("(?im)^\\s*RATIONALE\\s*:\\s*(.+?)\\s*$");

    private final HttpClient client;

    AnthropicLlmJudge() {
        this(HttpClient.newBuilder().connectTimeout(CONNECT_TIMEOUT).build());
    }

    AnthropicLlmJudge(HttpClient client) {
        this.client = client;
    }

    @Override
    public Optional<LlmVerdict> judge(String apiKey, CodeSubmission submission) {
        if (apiKey == null || apiKey.isBlank() || submission == null) {
            return Optional.empty();
        }

        try {
            HttpRequest request = HttpRequest.newBuilder(ENDPOINT)
                    .timeout(REQUEST_TIMEOUT)
                    .header("x-api-key", apiKey)
                    .header("anthropic-version", ANTHROPIC_VERSION)
                    .header("content-type", "application/json")
                    .POST(HttpRequest.BodyPublishers.ofString(
                            buildRequestBody(submission), StandardCharsets.UTF_8))
                    .build();

            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
            if (response.statusCode() != 200) {
                // Includes 401 on a bad key and 429 when rate limited. The body may
                // carry a message, but it is never logged -- it can echo request content.
                return Optional.empty();
            }
            return parseVerdict(response.body());

        } catch (InterruptedException e) {
            // Restore the flag rather than swallowing the interrupt outright.
            Thread.currentThread().interrupt();
            return Optional.empty();
        } catch (Exception e) {
            // IOException, timeouts, and anything the client throws unexpectedly. A
            // failure to reach the judge is a degraded analysis, never a failed batch.
            return Optional.empty();
        }
    }

    /**
     * Build the request body.
     *
     * <p>Hand-assembled, which is safe in one direction only: every interpolated value
     * is passed through {@link #escapeJson}, and the only variable content is the
     * submission source.
     */
    String buildRequestBody(CodeSubmission submission) {
        String source = submission.getSourceCode();
        if (source.length() > MAX_SOURCE_CHARS) {
            source = source.substring(0, MAX_SOURCE_CHARS);
        }

        String prompt = "You are assessing whether a piece of student source code was written "
                + "by a human or generated by a language model. Consider naming, structure, "
                + "comment style, and idiom.\n\n"
                + "Reply with EXACTLY two lines and nothing else:\n"
                + "LIKELIHOOD: <a number between 0.0 and 1.0>\n"
                + "RATIONALE: <one sentence>\n\n"
                + "Source:\n" + source;

        return "{\"model\":\"" + MODEL + "\","
                + "\"max_tokens\":1024,"
                + "\"messages\":[{\"role\":\"user\",\"content\":\"" + escapeJson(prompt) + "\"}]}";
    }

    /**
     * Extract a verdict from a response body, defensively.
     *
     * <p>Package-private and free of any network dependency on purpose: this is the part
     * that must survive hostile input, and it is fully unit-testable.
     *
     * @return the verdict, or empty if anything at all is wrong with the body
     */
    static Optional<LlmVerdict> parseVerdict(String body) {
        if (body == null || body.isBlank()) {
            return Optional.empty();
        }

        String text;
        try {
            text = String.join("\n", extractTextBlocks(body));
        } catch (RuntimeException e) {
            return Optional.empty();
        }
        if (text.isBlank()) {
            return Optional.empty();
        }

        Matcher likelihood = LIKELIHOOD.matcher(text);
        Matcher rationale = RATIONALE.matcher(text);
        if (!likelihood.find()) {
            return Optional.empty();
        }

        double value;
        try {
            value = Double.parseDouble(likelihood.group(1));
        } catch (NumberFormatException e) {
            return Optional.empty();
        }
        // A value outside [0,1] means the model misunderstood the task. Clamping would
        // silently turn "7.5" into a maximum-confidence accusation, so it is rejected.
        if (!Double.isFinite(value) || value < 0.0 || value > 1.0) {
            return Optional.empty();
        }

        String reason = rationale.find() ? rationale.group(1) : "no rationale supplied";
        return Optional.of(new LlmVerdict(value, reason, MODEL));
    }

    /**
     * Pull the decoded contents of every {@code "text": "..."} field out of the body.
     *
     * <p>Matches the key rather than the value, so the {@code "type":"text"} discriminator
     * is not mistaken for content. Thinking blocks, which carry no text under the default
     * display setting, contribute nothing and are skipped naturally.
     */
    static List<String> extractTextBlocks(String body) {
        List<String> blocks = new ArrayList<>();
        int index = 0;

        while (true) {
            int key = body.indexOf("\"text\"", index);
            if (key < 0) {
                break;
            }
            int cursor = key + "\"text\"".length();
            while (cursor < body.length() && Character.isWhitespace(body.charAt(cursor))) {
                cursor++;
            }
            if (cursor >= body.length() || body.charAt(cursor) != ':') {
                index = key + 1;
                continue;
            }
            cursor++;
            while (cursor < body.length() && Character.isWhitespace(body.charAt(cursor))) {
                cursor++;
            }
            if (cursor >= body.length() || body.charAt(cursor) != '"') {
                index = key + 1;
                continue;
            }

            StringBuilder decoded = new StringBuilder();
            int end = decodeJsonString(body, cursor, decoded);
            if (end < 0) {
                // Unterminated string: the body is truncated or malformed. Keep what
                // was decoded so far and stop rather than looping forever.
                blocks.add(decoded.toString());
                break;
            }
            blocks.add(decoded.toString());
            index = end;
        }
        return blocks;
    }

    /**
     * Decode one JSON string literal starting at the opening quote.
     *
     * @return the index just past the closing quote, or -1 if unterminated
     */
    private static int decodeJsonString(String body, int openQuote, StringBuilder out) {
        int i = openQuote + 1;

        while (i < body.length()) {
            char c = body.charAt(i);
            if (c == '"') {
                return i + 1;
            }
            if (c != '\\') {
                out.append(c);
                i++;
                continue;
            }
            if (i + 1 >= body.length()) {
                return -1;
            }
            char escape = body.charAt(i + 1);
            switch (escape) {
                case 'n' -> out.append('\n');
                case 't' -> out.append('\t');
                case 'r' -> out.append('\r');
                case 'b' -> out.append('\b');
                case 'f' -> out.append('\f');
                case '"' -> out.append('"');
                case '\\' -> out.append('\\');
                case '/' -> out.append('/');
                case 'u' -> {
                    if (i + 5 >= body.length()) {
                        return -1;
                    }
                    try {
                        out.append((char) Integer.parseInt(body.substring(i + 2, i + 6), 16));
                    } catch (NumberFormatException e) {
                        return -1;
                    }
                    i += 4;
                }
                default -> out.append(escape);
            }
            i += 2;
        }
        return -1;
    }

    static String escapeJson(String text) {
        StringBuilder out = new StringBuilder(text.length() + 16);
        for (int i = 0; i < text.length(); i++) {
            char c = text.charAt(i);
            switch (c) {
                case '"' -> out.append("\\\"");
                case '\\' -> out.append("\\\\");
                case '\n' -> out.append("\\n");
                case '\r' -> out.append("\\r");
                case '\t' -> out.append("\\t");
                case '\b' -> out.append("\\b");
                case '\f' -> out.append("\\f");
                default -> {
                    if (c < 0x20) {
                        out.append(String.format("\\u%04x", (int) c));
                    } else {
                        out.append(c);
                    }
                }
            }
        }
        return out.toString();
    }

    /** Never includes the API key, which is not held here in the first place. */
    @Override
    public String toString() {
        return "AnthropicLlmJudge[model=" + MODEL + "]";
    }
}
